### ISSUE TITLE
Thought Unscan was a video

### ISSUE THREAD

**Issue by jaxgeller** [minimill/minimill.co#107]
Yo looking real nice and clean guys, good work!  Also sick transition on the clicks of each portfolio item.

On mobile, you might want to scale down the play button arrow, because I thought unscan was a video. 

![image](https://cloud.githubusercontent.com/assets/4494509/13555579/1f04aa2a-e392-11e5-99d1-7fac6a146d34.png)

**Comment by jhil** [comment]
Valid concern. It is kinda meta with the screens and video icon, but that's the true screenshot from the website we created. If others raise this concern, we'll reconsider, but for now I think we'll leave it.
