### ISSUE TITLE
Change team page links

### ISSUE THREAD

**Issue by jhil** [minimill/minimill.co#110]
Dan: Github, Twitter, Personal Site
Jeff: Dribbble, Twitter, Personal Site
Amritha, ???, Twitter, Personal Site?

**Comment by schlosser** [comment]
Can you make me a globe icon or something for personal sites?

**Comment by jhil** [comment]
@danrschlosser 

Globe icon : https://www.dropbox.com/s/uiy8q83lp0q8ho7/icon-globe.svg?dl=0
