### ISSUE TITLE
Link client logos to websites

### ISSUE THREAD

**Issue by jhil** [minimill/minimill.co#118]
Open question. Might establish more validation.

Tipped by @mfburnett.

**Comment by jhil** [comment]
On hover, change svg fill to the darker gray color w/ standard color-hover transition time. Links are...
1. http://www.delta.com/
2. https://www.fin.com/
3. http://www.autodesk.com/
4. https://redspread.com/
5. http://upchannel.com/
6. https://creativemarket.com/
7. http://99percentinvisible.org/
8. https://unscan.com/

**Comment by schlosser** [comment]
It would be more work, but we could consider doing a primary color on hover, or the true color version of the svg.  What do you think?

**Comment by jhil** [comment]
@danrschlosser I like that idea, but some of them are multi-color logos (Delta, Autodesk, 99PI). We could use a primary color, but it might be more untrue than using a common color for all. Open for either.

**Comment by schlosser** [comment]
What do you think about having the true multi-color logos and then using the [CSS grayscale filter](https://css-tricks.com/almanac/properties/f/filter/) to gray them out when you're not hovering?

**Comment by jhil** [comment]
I like the consistency of the $light-gray logos. What about full-color svgs on hover that get `fill: $light-gray;` normally?

**Comment by schlosser** [comment]
sure!  Yeah that would be even better, forgot that grayscale wouldn't be
even.  Would you export those SVGs in color for me?

**Comment by jhil** [comment]
SVGs in color: https://www.dropbox.com/sh/9lhk5bww8bxeo9c/AABTrQO1a67ydOt6L8FAp7WGa?dl=0

**Comment by jhil** [comment]
over to you @danrschlosser :point_right:

**Comment by schlosser** [comment]
Alright!  This is live, but the Autodesk logo doesn't transition, because the `fill` property is a linear gradient, and you can't animate a linear gradient to a solid color... thoughts?

**Comment by jhil** [comment]
use the svgs here. all solid colors!

https://www.dropbox.com/sh/0pv3q3sja96qq9u/AADVV-4No1BkHh9xWNCW3AEda?dl=0

**Comment by jhil** [comment]
nice work @danrschlosser
