### ISSUE TITLE
Animation Glitch

### ISSUE THREAD

**Issue by jdt3969** [minimill/minimill.co#122]
https://www.youtube.com/watch?v=Nfj8krkm0a4&

Happens @ 11 second mark

**Comment by jhil** [comment]
Thanks for sharing, @jdt3969. @danrschlosser, I think we should just remove the animation from this background. Leave it static for more consistency and performance. :chart_with_upwards_trend:

**Comment by schlosser** [comment]
Not sure how I feel about this.  I think we could get the perf up with a bit of grease, it's a nice touch I think... but definitely not a must-keep.

**Comment by jhil** [comment]
I say kill the animation. On the actual site, it encourages clicking on the call to action. But on our site, it distracts from the content, making all the copy harder to read. And then there's the performance trade-off.

Keep the background. Ditch the translation.
