### ISSUE TITLE
Plug in Fin quote

### ISSUE THREAD

**Issue by jhil** [minimill/minimill.co#129]
"Minimill designed and developed a polished new website for us. As we started expanding our beta we were hoping to kick it up a notch and we definitely accomplished that."

Andrew Staub
Product, Fin

**Comment by jhil** [comment]
getting a headshot prepped now

**Comment by jhil** [comment]
![head-staub](https://cloud.githubusercontent.com/assets/2228347/14150803/dea8fed2-f678-11e5-9429-708c183e41e2.png)
![head-staub 2x](https://cloud.githubusercontent.com/assets/2228347/14150802/dea8d72c-f678-11e5-8f1c-43abdd96988b.png)

**Comment by jhil** [comment]
Not seeing this live. Any idea why?

**Comment by schlosser** [comment]
Deployed to the wrong server, will fix when I'm on wifi

**Comment by schlosser** [comment]
Deployed.
