### ISSUE TITLE
Darken social links

### ISSUE THREAD

**Issue by jhil** [minimill/minimill.co#135]
Right now they are our lightest gray and are hard to see at all unless hovered on. Can we knock the standard color (before hover) to the next darker gray?

**Comment by schlosser** [comment]
I think this is done, yea? Can we close out?

**Comment by jhil** [comment]
Not seeing any changes...

**Comment by jhil** [comment]
I'm aiming for these to behave exactly like the social links in the footer.

**Comment by schlosser** [comment]
oh lol got this confused with the company links, which was a previous issue.  Will fix this.
