### ISSUE TITLE
Color changing thresholds are off after resizing screen

### ISSUE THREAD

**Issue by jhil** [minimill/minimill.co#14]

**Comment by schlosser** [comment]
I think this is fixed, yea?  Otherwise please confirm

**Comment by jhil** [comment]
No it's not fixed :(

I'll demonstrate on our call

**Comment by schlosser** [comment]
Please confirm after this update

**Comment by schlosser** [comment]
Ohhh just ran into a super interesting bug with this: what happens when you want to resize and scroll at the same time (which happens if you use areo snap)?

Well, I solved that problem, so I believe this should be fixed.
