### ISSUE TITLE
Finalize project order

### ISSUE THREAD

**Issue by jhil** [minimill/minimill.co#15]
I think Fin should go first, but this is a later stage step.

**Comment by jhil** [comment]
I say
1. Fin
2. WAC
3. UpChannel
4. Unscan

Thoughts?

**Comment by schlosser** [comment]
That works for me

**Comment by jhil** [comment]
Actually scratch that. We agreed WAC would come first so that the transition was blue-yellow-blue, not blue-blue-yellow.

WAC
Fin
UpChannel
Unscan

final answer (.......i think)
