### ISSUE TITLE
Add pixel icons

### ISSUE THREAD

**Issue by jhil** [minimill/minimill.co#19]
- [x] x in contact page
- [x] quote in project views
- [x] view project link arrows

**Comment by schlosser** [comment]
I ended up doing the project link arrows in CSS after all

**Comment by jhil** [comment]
That's ok! CSS might even be better for all of them??? IDK

**Comment by jhil** [comment]
Also the down arrow on homepage (that was added later)

**Comment by jhil** [comment]
- [ ] down arrow on homepage

**Comment by jhil** [comment]
closing this and making a new issue for the down arrow since it involves a different discussion
