### ISSUE TITLE
Create team page

### ISSUE THREAD

**Issue by jhil** [minimill/minimill.co#22]

**Comment by jhil** [comment]
Team photos: https://www.dropbox.com/sh/bya5x4pfgav8us0/AACeov_HIhW0UcZL5N_7bFiXa?dl=0

**Comment by jhil** [comment]
![amritha-slice](https://cloud.githubusercontent.com/assets/2228347/12769046/4ae270f6-c9e2-11e5-9f69-b81f67a123fc.png)
![amritha-slice 2x](https://cloud.githubusercontent.com/assets/2228347/12769047/4ae3e6a2-c9e2-11e5-9c91-5baa80d8419d.png)
![dan-slice](https://cloud.githubusercontent.com/assets/2228347/12769045/4ae226b4-c9e2-11e5-87b7-577741227239.png)
![dan-slice 2x](https://cloud.githubusercontent.com/assets/2228347/12769048/4ae53372-c9e2-11e5-8b14-9c3f27a8e50e.png)
![jeff-slice](https://cloud.githubusercontent.com/assets/2228347/12769049/4ae694d8-c9e2-11e5-90e3-56b327ea8e3d.png)
![jeff-slice 2x](https://cloud.githubusercontent.com/assets/2228347/12769044/4ae1540a-c9e2-11e5-874f-4fd12a4546ac.png)

**Comment by schlosser** [comment]
Is the zeplin mock the final version?  Should we have any other info on the team page other than our names / roles / pics?  Join the team?  Email us individually?  mini bio?  twitter / website?

**Comment by jhil** [comment]
I like the minimalism of it, but it is pretty barren. Open to suggestions

**Comment by jhil** [comment]
woooooo so excited to check this out

**Comment by jhil** [comment]
firee

**Comment by schlosser** [comment]
broken!!

**Comment by schlosser** [comment]
wait

**Comment by schlosser** [comment]
:see_no_evil:
