### ISSUE TITLE
Client logos in SVG?

### ISSUE THREAD

**Issue by jhil** [minimill/minimill.co#25]

**Comment by jhil** [comment]
(They're currently PNG)

**Comment by schlosser** [comment]
That would be nice, if we can get them

**Comment by jhil** [comment]
Yeah I already have all of them. Just gotta export properly.

**Comment by jhil** [comment]
Exported here! https://www.dropbox.com/sh/53c4bx94fjndk40/AACMhGKaA_CGLw5Hv0mQnZDya?dl=0

**Comment by jhil** [comment]
over to you @danrschlosser :point_right:
