### ISSUE TITLE
Link entire pullout card to external project

### ISSUE THREAD

**Issue by jhil** [minimill/minimill.co#32]
Clicking anywhere in this box should link

![image](https://cloud.githubusercontent.com/assets/2228347/12683035/cb7f4d12-c684-11e5-9332-8faa26c50d7c.png)

**Comment by schlosser** [comment]
Done, unless you want a hover state

**Comment by jhil** [comment]
background: minimill blue
color / icon fill: white

**Comment by jhil** [comment]
making a new issue for ^ to stay organized
