### ISSUE TITLE
Pullout card color changing?

### ISSUE THREAD

**Issue by jhil** [minimill/minimill.co#33]
Should we shift the colors here (minimill blue)?

<img width="1326" alt="screen shot 2016-01-29 at 12 36 07 pm" src="https://cloud.githubusercontent.com/assets/2228347/12683053/efc4da16-c684-11e5-8de5-36897caeaa16.png">

**Comment by schlosser** [comment]
Not sure what you mean by that, shift what colors?

**Comment by schlosser** [comment]
I thought about this a bit and I'm not sure we need it.  

What do you think @jhil?
