### ISSUE TITLE
Remove navbar from contact page?

### ISSUE THREAD

**Issue by jhil** [minimill/minimill.co#34]
What do you think? It gets weird when this happens

<img width="1440" alt="screen shot 2016-01-29 at 12 37 56 pm" src="https://cloud.githubusercontent.com/assets/2228347/12683089/2d513a1e-c685-11e5-8b23-431aa235fc3b.png">

**Comment by schlosser** [comment]
I could fade out the navbar behind, if you like that better

**Comment by schlosser** [comment]
resolved: full opacity
