### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by jhil** [minimill/minimill.co#35]
Insert the old one for the time being, but I think I'd like to update it to a blue circle with the M inside

**Comment by jhil** [comment]
- [x] add current favicon
- [ ] create new favicon
- [ ] add new favicon

**Comment by schlosser** [comment]
The current favicon is there for me.

![screen shot 2016-02-03 at 2 22 03 pm](https://cloud.githubusercontent.com/assets/2433509/12794108/86bb3e24-ca81-11e5-88fb-98167cf939fe.png)

**Comment by jhil** [comment]
FAVICONS HOT OFF THE PRESSES AT ALL SIZES :rocket: 

https://www.dropbox.com/sh/8zjedjqyzqenquy/AABZUfontJZZylbz1n3mklrma?dl=0

**Comment by jhil** [comment]
:fire:
