### ISSUE TITLE
Background "flash" in footer

### ISSUE THREAD

**Issue by jhil** [minimill/minimill.co#39]
![footer-flash](https://cloud.githubusercontent.com/assets/2228347/12769178/9c8469b8-c9e3-11e5-816b-c5a4b17bebaa.gif)

**Comment by schlosser** [comment]
Hmmmmm not sure what this was but it wasn't happening for me locally (I could replicate in deployment) so I redeployed and it went away... 

Keep your :eyes: out for this, but I'm closing for now

**Comment by schlosser** [comment]
Figured this out, it was for strange reasons (when you transition between background colors, it messes up.  it's fixed :)

**Comment by jhil** [comment]
good catch

**Comment by jhil** [comment]
Flash is back! Only on scroll-up

**Comment by jhil** [comment]
![scrollflash](https://cloud.githubusercontent.com/assets/2228347/12834817/917cdff0-cb78-11e5-9acd-e3a220340093.gif)

**Comment by schlosser** [comment]
:boom: 

``` scss
// All backgrounds after the current section should be invisible.
.background-#{$current-section} ~ li {
    @extend %hidden;
}
```
