### ISSUE TITLE
remove line breaks when text doesn't fit on one line

### ISSUE THREAD

**Issue by jhil** [minimill/minimill.co#4]
only for the second line. "we are minimill," should always be on its own line.

<img width="198" alt="screen shot 2015-08-26 at 5 16 16 pm" src="https://cloud.githubusercontent.com/assets/2228347/9509573/31e903ac-4c16-11e5-8e68-ec84155d6d53.png">

**Comment by schlosser** [comment]
The lowest screen width I was planning on supporting was 320px (iPhone 4). 

Do you see any reason why we should support lower than that?  I suppose people inspecting and shrinking the viewport...

**Comment by jhil** [comment]
haha that's how i found this. if you think it'll never come up, that's fine. though i dont think a line or two of css to solve for that would be terrible.

**Comment by schlosser** [comment]
:+1:
