### ISSUE TITLE
Lots and lots of hover styles

### ISSUE THREAD

**Issue by schlosser** [minimill/minimill.co#43]
animations?
color changes?

**Comment by jhil** [comment]
ELEMENTS
- [ ] navbar
- [ ] navbar logo
- [ ] footer hover
- [ ] footer logo
- [ ] "let's work together" email
- [ ] social links in footer

HOME
- [ ] down arrow

WORK
- [ ] view project link
- [ ] featured work image
- [ ] client logo

PROJECT
- [ ] pullout card
- [ ] text link in body

CONTACT
- [ ] x icon
- [ ] "let's work together" email
- [ ] social icons

TEAM
- [ ] team member
- [ ] social icons

**Comment by jhil** [comment]
Making separate issues for each one.
