### ISSUE TITLE
Laptop asset without spacing

### ISSUE THREAD

**Issue by schlosser** [minimill/minimill.co#44]

**Comment by jhil** [comment]
https://www.dropbox.com/sh/1cziji8fd60kqtw/AAA0eQOaU5SIbN1KiIIwy4VZa?dl=0

**Comment by jhil** [comment]
![fin-macbook-noshadow](https://cloud.githubusercontent.com/assets/2228347/12909348/5318cef0-cece-11e5-9265-8436d2d33b3a.png)
![unscan-macbook-noshadow](https://cloud.githubusercontent.com/assets/2228347/12909349/531a95dc-cece-11e5-930e-3f9a26cf7bba.png)
![upchannel-macbook-noshadow](https://cloud.githubusercontent.com/assets/2228347/12909350/531bd442-cece-11e5-86e4-a12caa5b1325.png)
![wac-macbook-noshadow](https://cloud.githubusercontent.com/assets/2228347/12909351/531de7c8-cece-11e5-9735-47a75128e96d.png)

**Comment by jhil** [comment]
made a branch and a PR. not sure if you wanted me to do this, but i was playing around ;) 

#47 - https://github.com/minimill/minimill.co/pull/47
