### ISSUE TITLE
Logo link doesn't work on #contact

### ISSUE THREAD

**Issue by jhil** [minimill/minimill.co#57]
![contact](https://cloud.githubusercontent.com/assets/2228347/13194909/7110d99e-d76f-11e5-8fe2-6480628024f4.gif)

**Comment by schlosser** [comment]
I can't replicate this, can you try a hard refresh and then replicate?

**Comment by jhil** [comment]
Yup. Still happened. Just press Contact on load, then the Minimill logo. I'm in Chrome.

**Comment by schlosser** [comment]
browser size?

**Comment by schlosser** [comment]
Still completely unable to reproduce :((((

**Comment by jhil** [comment]
I wonder if it's a cerberus issue?

**Comment by jhil** [comment]
I demonstrated it to you when we were together though, right? Just confirm I'm not crazy?

**Comment by schlosser** [comment]
yes we did confirm that.

**Comment by schlosser** [comment]
beta.minimill.co isn't run off cerberus though, which is strange...

**Comment by schlosser** [comment]
Just had a possible breakthrough, interested if this is fixed for you @jhil

**Comment by jhil** [comment]
nope :/

**Comment by schlosser** [comment]
@jhil Can you confirm that this is still happening?

**Comment by jhil** [comment]
zomg even this works too!

**Comment by jhil** [comment]
:raised_hands:

**Comment by schlosser** [comment]
Amazing!!
