### ISSUE TITLE
Work nav link to first project

### ISSUE THREAD

**Issue by jhil** [minimill/minimill.co#62]
When the user clicks `Work` from any page, it should load the homepage scrolled down to the first project. Currently, it just redirects to `/`

**Comment by schlosser** [comment]
Hmmm, I think that might be confusing.  Being dropped on the page with no indication that you can scroll would be weird.  We avoid this problem on the home page with the arrow, but unless we put them on every section (which we shouldn't do IMO) it might be disorienting to be dropped straight into WAC.
