### ISSUE TITLE
Typography sample hovers

### ISSUE THREAD

**Issue by jhil** [minimill/minimill.co#65]
the baseline starts at opacity: .25, and animates in from left-to-right at opacity: 1. i achieved this in principle by creating two lines, one of full length, .25 opacity, and the other of full length and opacity: 1, but scaled the x of the second to zero around its leftmost origin. then restore the other state on the hover of the text block.

![text-hover-3](https://cloud.githubusercontent.com/assets/2228347/13271203/6666563c-da61-11e5-82c4-9e6fa56fec62.gif)

**Comment by schlosser** [comment]
Done except for mobile, for which there is another open issue.

**Comment by jhil** [comment]
Right. Well the hovers shouldnt work on mobile anyway. We'll just remove the effect entirely
