### ISSUE TITLE
Center projects on mobile

### ISSUE THREAD

**Issue by jhil** [minimill/minimill.co#69]
For example

![project-upchannel](https://cloud.githubusercontent.com/assets/2228347/13271535/96b3b3e6-da63-11e5-8ef4-9ced690bc06c.png)

vs

![screen shot 2016-02-23 at 7 28 31 pm](https://cloud.githubusercontent.com/assets/2228347/13271541/a27f2a66-da63-11e5-9a5f-a1f516a19db6.png)

**Comment by jhil** [comment]
Alternatively, we could switch to a less heavy system where the background boxes are not as big (more based on padding of content than screen size). let me know what you think

**Comment by schlosser** [comment]
So I'm less of a fan on the perfectly full screen panes, especially if we're not doing scroll jacking.  They're not going to land perfectly positioned, so I think it's better to just size them using padding.

**Comment by jhil** [comment]
Ok padding it is!
