### ISSUE TITLE
Fix blue footer

### ISSUE THREAD

**Issue by jhil** [minimill/minimill.co#72]
not sure why this happened. did you tweak any responsive/background code recently? screenshot at `960px` screen width

<img width="849" alt="screen shot 2016-02-23 at 6 55 57 pm" src="https://cloud.githubusercontent.com/assets/2228347/13271645/6295b4dc-da64-11e5-92ee-f3e0b604227c.png">

**Comment by schlosser** [comment]
Should be fixed, would you try to reproduce this?

**Comment by jhil** [comment]
Still here. this screenshot is at 1280px. i think it happened when i switched from a smaller window width to this one.

![screen shot 2016-02-24 at 10 09 35 pm](https://cloud.githubusercontent.com/assets/2228347/13308679/78016b74-db43-11e5-84a3-3c6860cdeefb.png)
