### ISSUE TITLE
Insert final assets into project pages

### ISSUE THREAD

**Issue by jhil** [minimill/minimill.co#76]
Final assets needed.

**Comment by schlosser** [comment]
Feel free to edit this comment and insert your own assets into this checklist:
- [ ] SVG assets for typography samples
- [x] WAC video
- [x] Upchannel video?
- [x] Upchannel branding
- [x] Unscan branding?
- [x] Social media assets?

**Comment by jhil** [comment]
- [ ] higher quality fin animation
- [ ] fin phone animation

**Comment by jhil** [comment]
WAC
- wac video (questionable, discuss mov vs gif): https://www.dropbox.com/s/n0k4hbuq9bcnyit/wac-animation-2-trimmed.mov?dl=0

UPCHANNEL
- logotype: https://www.dropbox.com/s/0jp8jyws7lff42t/upchannel-logotype.svg?dl=0
- shirt womens: https://www.dropbox.com/s/e6ru3fdna99r2md/upchannel-shirt-women-trans.png?dl=0
- shirt mens: https://www.dropbox.com/s/q2inn1sfw6ip5e9/upchannel-shirt-mens-trans.png?dl=0

**Comment by jhil** [comment]
UNSCAN
- logotype: https://www.dropbox.com/s/c2wst0xkwcon0fa/unscan-logotype.svg?dl=0
- richard 1x: https://www.dropbox.com/s/8u33n0ckkekmf17/head-richard.png?dl=0, richard 2x: https://www.dropbox.com/s/u06h8wej34tgel3/head-richard%402x.png?dl=0
- animation: https://www.dropbox.com/s/sfs2nfu42hawpze/unscan-logo-animation-7-2.gif?dl=0
- illustrations: https://www.dropbox.com/sh/9w4rmil28ds71xi/AAD9DbqCCT7536W9q6iK2YIUa?dl=0 (should we use `...presentation.png` or individual svgs?)
- imagery woman 1x: https://www.dropbox.com/s/6hdhtpv4aox9oxq/Testimonial%20Photo.png?dl=0, imagery woman 2x: https://www.dropbox.com/s/85j5a46vsu5tg42/Testimonial%20Photo%402x.png?dl=0
- imagery office 1x: https://www.dropbox.com/s/4ysfm9uzqa2if1d/Office%20Photo.png?dl=0, imagery office 2x: https://www.dropbox.com/s/bptrmge9vcaqp9q/Office%20Photo%402x.png?dl=0
