### ISSUE TITLE
Minimill Logo / text is off by a pixel

### ISSUE THREAD

**Issue by schlosser** [minimill/minimill.co#8]
Looky here:  Because the font does not perfectly left-align in it's box, the minimill logo is off by a pixel.

Possible solutions include adding a pixel margin (negative or positive) to compensate.  Or, transforms?

Thoughts @jhil?

<img width="37" alt="screen shot 2015-09-04 at 1 03 59 am" src="https://cloud.githubusercontent.com/assets/2433509/9676923/03d6fba4-52a1-11e5-85fe-ac148e7e81e3.png">

**Comment by jhil** [comment]
It's fine. that just happens sometimes with text rendering and i worry that any tweaks would make weird edge cases.

crazy observance though hahaha
