### ISSUE TITLE
White text on page transition sometimes

### ISSUE THREAD

**Issue by schlosser** [minimill/minimill.co#81]

**Comment by jhil** [comment]
What was the problemo?

**Comment by schlosser** [comment]
In Pageanimation.js, when we apply the class to the body that causes the page transition animations, we were _setting_ the body class instead of _adding_ a body class.  This meant that the body class that was maintaining the section-specific styles was being removed by pageanimation.js

The fix was easy: https://github.com/minimill/pageanimation.js/commit/4e92763f142e65f3d76caa46be714494175645a6#diff-a5d7664a1a8fffc352f27424c141a42eL289

**Comment by jhil** [comment]
:ok_hand:
