### ISSUE TITLE
Logo link doesn't work on /team

### ISSUE THREAD

**Issue by jhil** [minimill/minimill.co#83]
New problem... sometimes this redirects to `https://beta.minimill.co/team/undefined`

Can't reproduce atm, but I'll get back to you when I can

**Comment by jhil** [comment]
Maybe this is related to #57 ? Could it be a problem with the link route itself? Or the logo file or something?

**Comment by schlosser** [comment]
I think it's something to do with pageanimation.js on that page. but I'm not sure why....

**Comment by jhil** [comment]
works now :+1:
