### ISSUE TITLE
Slide nav down after delay on #contact

### ISSUE THREAD

**Issue by jhil** [minimill/minimill.co#85]
Helps the user focus on the action at hand, and could win IxN brownie points.

**Comment by schlosser** [comment]
This is deployed on beta, but I don't think it looks very good.

Let me know what you think and I deploy it or revert.

**Comment by jhil** [comment]
yeah it doesnt look great, plus i got used to the site without it. revert and call it a day

**Comment by jhil** [comment]
thanks @danrschlosser
